sentence = input('What is you sentence')
sentence = sentence.replace("!", "#")
sentence = sentence.replace("@", "#")
sentence = sentence.replace("$", "#")
sentence = sentence.replace("%", "#")
sentence = sentence.replace("^", "#")
sentence = sentence.replace("&", "#")
sentence = sentence.replace("*", "#")
sentence = sentence.replace("(", "#")
sentence = sentence.replace(")", "#")
sentence = sentence.replace("?", "#")
sentence = sentence.replace("/", "#")
sentence = sentence.replace("<", "#")
sentence = sentence.replace(">", "#")
sentence = sentence.replace("[", "#")
sentence = sentence.replace("]", "#")
sentence = sentence.replace("+", "#")
sentence = sentence.replace("=", "#")
sentence = sentence.replace("-", "#")
sentence = sentence.replace("~", "#")
sentence = sentence.replace("_", "#")
sentence = sentence.replace("`", "#")
sentence = sentence.replace("|", "#")
print(sentence)
